export enum ErrorCode {
  OK = 'OK',
  ERR_ILLEGAL_ACTION = 'ERR_ILLEGAL_ACTION',
  ERR_TIMEOUT = 'ERR_TIMEOUT',
  ERR_ENV_NOT_FOUND = 'ERR_ENV_NOT_FOUND',
  ERR_REPLAY_NOT_FOUND = 'ERR_REPLAY_NOT_FOUND',
  ERR_INTERNAL = 'ERR_INTERNAL',
}
